### ISSUE TITLE
Honor code violation

### ISSUE THREAD

**Issue by lam2mo** [Davileet/ParallelPrograms-CS470#1]
Can you please make this repo private?

It contains solutions to class projects. Posting these solutions publicly is a violation of the JMU honor code. You are welcome to share your solutions with interviewers and include them in a portfolio as examples of your work, but they should not be posted publicly.

thanks,
-- lam

**Comment by Davileet** [comment]
Taken care of, sorry about that.

**Comment by lam2mo** [comment]
Can you actually make the repository private or delete it? The code is still available if someone clones the repository and checks out an older commit.

thanks,
-- lam




On Feb 10, 2017, at 1:09 PM, Davileet <notifications@github.com<mailto:notifications@github.com>> wrote:


Taken care of, sorry about that.

**Comment by Davileet** [comment]
Sorry, didn't realize that. I'm new to github, but yes I will delete the
repository also.
